name: Node@Latest Test
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build_and_test:
    name: Build and Test Latest Ubuntu and Node Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: latest

      - name: Install NPM
        run: npm install -g npm

      - name: Install Dependencies
        run: | 
          npm ci --ignore-scripts
          cd server
          npm ci --ignore-scripts
          cd ../client
          npm ci --ignore-scripts

      - name: Run Test Suites
        run: npm test