name: Node@v15
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    name: Test on Ubuntu Latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with: 
          node-version: 15

      - name: Install Dependencies
        run: | 
          npm ci --ignore-scripts
          cd server
          npm ci --ignore-scripts
          cd ../client
          npm ci --ignore-scripts

      - name: Run Test Suites
        run: npm test